import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.58.0';
const supabase=createClient('https://vwajndkxlpgkkdutebhn.supabase.co','sb_publishable_FwMIHia6cfjGhU_uZmSYfw_eIuQDmVJ');
window.CBS_SUPABASE=supabase;
let signup=false;
const gate=document.querySelector('#authGate'),app=document.querySelector('#app'),form=document.querySelector('#authForm'),msg=document.querySelector('#authMessage'),toggle=document.querySelector('#authToggle'),name=document.querySelector('#authName');
function mode(){document.querySelector('#authTitle').textContent=signup?'Create account':'Sign in';document.querySelector('#authSubmit').textContent=signup?'Create account':'Sign in';toggle.textContent=signup?'Already have an account? Sign in':'Create an account';name.parentElement.style.display=signup?'block':'none';}
toggle.onclick=()=>{signup=!signup;msg.textContent='';mode()};
form.onsubmit=async e=>{e.preventDefault();msg.textContent='Please wait…';const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;if(signup){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name.value.trim()}}});msg.textContent=error?error.message:'Account created. Check your email if confirmation is required, then sign in.';}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)msg.textContent=error.message;else await enter();}};
async function enter(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;gate.classList.add('hidden');app.classList.remove('hidden');window.CBS_USER=user;const {data:members}=await supabase.from('memberships').select('organization_id,role,organizations(id,name,industry,base_currency,plan)').eq('active',true);window.CBS_MEMBERSHIPS=members||[];if(members?.length){const o=members[0].organizations;localStorage.setItem('cbsState',JSON.stringify({name:o.name,industry:o.industry,currency:o.base_currency,size:'',plan:o.plan,data:{sales:[],expenses:[],staff:[],inventory:[],projects:[],guests:[],reservations:[]},modules:{},organizationId:o.id,role:members[0].role}));}else localStorage.removeItem('cbsState');const s=document.createElement('script');s.src='/script.js';document.body.appendChild(s);}
const {data:{session}}=await supabase.auth.getSession();if(session)await enter();else mode();